"use client";

import Link from "next/link";
import { ArrowLeft, CheckCircle2, ExternalLink, FolderKanban, Globe, Server, StickyNote } from "lucide-react";
import { Badge, Button, Card, CardContent, CardHeader, CardTitle, StatusBadge } from "@/components/ui";
import { type ServiceSite, type ServiceStatus, type RuntimeType, type VerificationSource } from "@/data/services";
import { projects } from "@/data/projects";
import { vpsServers } from "@/data/vps";
import { ServiceIconView } from "@/components/services/service-icons";

const statusMeta: Record<ServiceStatus, { label: string; tone: "success" | "neutral" | "danger" | "warning" | "info" }> = { running: { label: "运行中", tone: "success" }, stopped: { label: "已停止", tone: "neutral" }, error: { label: "异常", tone: "danger" }, maintaining: { label: "待核验", tone: "warning" }, external: { label: "外部服务", tone: "info" } };
const runtimeLabels: Record<RuntimeType, string> = { systemd: "systemd", docker: "Docker", pm2: "PM2", external: "外部服务", unknown: "待确认" };
const sourceLabels: Record<VerificationSource, string> = { ssh: "SSH 只读核验", komari: "Komari 监控", user: "用户确认", unknown: "尚无核验记录" };

export function ServiceStatusBadge({ status, pulse = false }: { status: ServiceStatus; pulse?: boolean }) { const meta = statusMeta[status]; return <StatusBadge tone={meta.tone} pulse={pulse && status === "running"}>{meta.label}</StatusBadge>; }

export function ServiceDetail({ service }: { service: ServiceSite }) {
  const linkedProjects = projects.filter((p) => service.projectIds.includes(p.id) || p.serviceIds.includes(service.id));
  const linkedVps = vpsServers.filter((v) => service.vpsIds.includes(v.id) || linkedProjects.some((p) => p.vpsId === v.id));
  return <div className="animate-rise-in min-w-0 space-y-3"><Link href="/services" className="inline-flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="h-4 w-4" />返回服务管理</Link><div className="flex flex-col gap-4 md:flex-row md:items-start md:justify-between"><div className="flex min-w-0 items-start gap-3"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-lg border border-border bg-elevated text-primary"><ServiceIconView icon={service.icon} className="h-5 w-5" /></span><div><div className="flex flex-wrap items-center gap-2"><h1 className="text-xl font-semibold tracking-tight sm:text-2xl">{service.name}</h1><ServiceStatusBadge status={service.status} pulse /></div><p className="mt-1 text-sm text-muted-foreground">{service.description}</p></div></div>{service.url ? <a href={service.url} target="_blank" rel="noreferrer"><Button><ExternalLink className="h-4 w-4" />打开服务</Button></a> : <Badge variant="neutral">暂无访问地址</Badge>}</div>
    <div className="grid gap-3 lg:grid-cols-3"><Card><CardHeader><CardTitle>服务状态</CardTitle></CardHeader><CardContent className="space-y-3"><ServiceStatusBadge status={service.status} pulse /><div className="text-sm text-muted-foreground">分类：{service.category}</div></CardContent></Card><Card className="lg:col-span-2"><CardHeader><CardTitle>运行信息</CardTitle></CardHeader><CardContent className="grid gap-3 text-sm sm:grid-cols-2"><Info label="运行方式" value={runtimeLabels[service.runtimeType]} /><Info label="运行标识" value={service.runtimeName} /><Info label="监听端口" value={service.port} /><Info label="最后核验" value={service.lastVerifiedAt} /></CardContent></Card></div>
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-primary" />数据可信度</CardTitle></CardHeader><CardContent className="flex flex-wrap items-center gap-3 text-sm"><Badge variant={service.verificationSource === "user" ? "warning" : service.verificationSource === "unknown" ? "neutral" : "success"}>{sourceLabels[service.verificationSource]}</Badge><span className="text-muted-foreground">状态仅代表当前记录，不执行真实运维操作。</span></CardContent></Card>
    <div className="grid gap-3 lg:grid-cols-2"><Card><CardHeader><CardTitle>所属 Project</CardTitle></CardHeader><CardContent className="space-y-2">{linkedProjects.length ? linkedProjects.map((p) => <Link key={p.id} href={`/projects/${p.id}`} className="flex items-center justify-between rounded-md border border-border px-3 py-2 text-sm hover:bg-elevated"><span className="flex items-center gap-2"><FolderKanban className="h-4 w-4 text-muted-foreground" />{p.name}</span><span className="text-xs text-muted-foreground">{p.vpsName}</span></Link>) : <p className="text-sm text-muted-foreground">暂无关联项目。</p>}</CardContent></Card><Card><CardHeader><CardTitle>运行 VPS</CardTitle></CardHeader><CardContent className="space-y-2">{linkedVps.length ? linkedVps.map((v) => <Link key={v.id} href={`/servers/${v.id}`} className="flex items-center justify-between rounded-md border border-border px-3 py-2 text-sm hover:bg-elevated"><span className="flex items-center gap-2"><Server className="h-4 w-4 text-muted-foreground" />{v.name}</span><span className="text-xs text-muted-foreground">{v.region} · {v.status === "online" ? "在线" : v.status}</span></Link>) : <p className="text-sm text-muted-foreground">外部服务，不运行在已管理 VPS 上。</p>}</CardContent></Card></div>
    <Card><CardHeader><CardTitle>描述、备注与访问地址</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><p>{service.description}</p><div className="flex gap-2 border-t border-border pt-3 text-muted-foreground"><StickyNote className="mt-0.5 h-4 w-4 shrink-0" /><p>{service.notes || "暂无备注。"}</p></div><div className="flex items-center gap-2 border-t border-border pt-3"><Globe className="h-4 w-4 text-muted-foreground" />{service.url ? <a href={service.url} target="_blank" rel="noreferrer" className="truncate text-primary hover:underline">{service.url}</a> : <span className="text-muted-foreground">未配置访问地址</span>}</div></CardContent></Card>
  </div>;
}
function Info({ label, value }: { label: string; value: string }) { return <div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 break-words font-medium">{value}</p></div>; }
