"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { FileText, Plus, Search, Trash2, X } from "lucide-react";
import { Badge, Button, Card } from "@/components/ui";
import { noteCategories, type Note, type NoteCategory } from "@/data/notes";

export function NotesList() {
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState("全部");
  const [modalOpen, setModalOpen] = useState(false);
  const [allNotes, setAllNotes] = useState<Note[]>([]);
  const [title, setTitle] = useState("");
  const [categoryDraft, setCategoryDraft] = useState<NoteCategory>("其他");
  const [tags, setTags] = useState("");
  const [content, setContent] = useState("");
  const [error, setError] = useState("");
  const loadNotes = async () => { const response = await fetch("/api/notes", { cache: "no-store" }); if (!response.ok) throw new Error("加载笔记失败"); setAllNotes(await response.json() as Note[]); };
  useEffect(() => { loadNotes().catch(() => setError("笔记加载失败，请稍后重试。")); }, []);
  const filtered = useMemo(() => allNotes.filter((note) => { const text = [note.title, note.excerpt, note.description, note.category, ...note.tags].join(" ").toLowerCase(); return (!query || text.includes(query.toLowerCase())) && (category === "全部" || note.category === category); }), [allNotes, category, query]);
  const clearFilters = () => { setQuery(""); setCategory("全部"); };
  const closeForm = () => { setModalOpen(false); setTitle(""); setCategoryDraft("其他"); setTags(""); setContent(""); setError(""); };
  const createNote = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setError(""); const response = await fetch("/api/notes", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title, category: categoryDraft, tags: tags.split(",").map((tag) => tag.trim()).filter(Boolean), content }) }); if (!response.ok) { setError("保存失败，请检查标题、分类和内容。"); return; } const created = await response.json() as Note; setAllNotes((current) => [created, ...current]); closeForm(); };
  const removeNote = async (note: Note) => { if (!window.confirm(`确定删除笔记“${note.title}”吗？`)) return; setError(""); const response = await fetch(`/api/notes?id=${encodeURIComponent(note.id)}`, { method: "DELETE" }); if (!response.ok) { setError("删除失败，请稍后重试。"); return; } setAllNotes((current) => current.filter((item) => item.id !== note.id)); };
  return <div className="animate-rise-in min-w-0 space-y-4">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-xl font-semibold tracking-tight sm:text-2xl">笔记文档</h1><p className="mt-2 text-sm text-muted-foreground">记录技术实践、配置经验和个人知识。</p></div><Button className="w-full shrink-0 sm:w-auto" onClick={() => setModalOpen(true)}><Plus className="h-4 w-4" />新建笔记</Button></div>
    <Card className="p-3"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索标题、描述、标签或分类" className="h-10 w-full rounded-md border border-border bg-background pl-9 pr-3 text-sm outline-none focus:border-primary" /></div><div className="mt-3 flex gap-2 overflow-x-auto pb-1">{["全部", ...noteCategories].map((item) => <button key={item} onClick={() => setCategory(item)} className={`rounded-md border px-3 py-1.5 text-xs shrink-0 min-h-8 transition-colors ${category === item ? "border-primary bg-primary/10 text-primary" : "border-border text-muted-foreground hover:bg-elevated"}`}>{item}</button>)}</div></Card>
    {error && <div className="rounded-md border border-danger/30 bg-danger/10 px-3 py-2 text-sm text-danger">{error}</div>}
    <Card className="min-w-0 overflow-hidden"><div className="flex items-center justify-between border-b border-border px-4 py-3 text-sm"><span>全部笔记</span><span className="text-xs text-muted-foreground">共 {filtered.length} 篇</span></div><div className="divide-y divide-border">{filtered.map((note) => <div key={note.id} className="flex min-w-0 items-start gap-3 px-4 py-3 transition-colors hover:bg-elevated/50"><Link href={`/notes/${note.slug}`} className="flex min-w-0 flex-1 items-start gap-3"><span className="mt-0.5 flex h-8 w-8 shrink-0 items-center justify-center rounded-md border border-border bg-elevated"><FileText className="h-4 w-4 text-primary" /></span><span className="min-w-0 flex-1"><span className="flex flex-wrap items-center gap-2"><span className="font-medium">{note.title}</span><Badge variant="info">{note.category}</Badge></span><span className="mt-1 block text-xs text-muted-foreground">{note.excerpt}</span><span className="mt-2 flex flex-wrap gap-1.5">{note.tags.map((tag) => <Badge key={tag}>{tag}</Badge>)}</span></span><span className="shrink-0 text-xs text-muted-foreground">{note.updatedAt}</span></Link><Button variant="ghost" size="icon" aria-label={`删除${note.title}`} title="删除笔记" onClick={() => removeNote(note)}><Trash2 className="h-4 w-4 text-danger" /></Button></div>)}{filtered.length === 0 && <div className="p-10 text-center"><p className="text-sm text-muted-foreground">{error ? "" : "没有找到匹配的笔记"}</p><Button variant="ghost" size="sm" className="mt-2" onClick={clearFilters}><X className="h-3.5 w-3.5" />清除筛选</Button></div>}</div></Card>
    {modalOpen && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4" role="dialog" aria-modal="true" aria-labelledby="new-note-title"><Card className="max-h-[calc(100dvh-2rem)] w-full max-w-lg overflow-y-auto p-4 sm:p-5"><div className="flex items-center justify-between"><div><h2 id="new-note-title" className="font-semibold">新建笔记</h2><p className="mt-1 text-xs text-muted-foreground">保存后会写入本地 SQLite，刷新和重启后仍保留。</p></div><Button variant="ghost" size="icon" aria-label="关闭" onClick={closeForm}><X className="h-4 w-4" /></Button></div><form className="mt-4 grid gap-4" onSubmit={createNote}><label className="grid gap-1.5 text-xs font-medium">标题<input required value={title} onChange={(event) => setTitle(event.target.value)} className="h-9 rounded-md border border-input bg-background px-3 text-sm outline-none focus:border-primary" placeholder="例如：本周运维记录" /></label><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-1.5 text-xs font-medium">分类<select value={categoryDraft} onChange={(event) => setCategoryDraft(event.target.value as NoteCategory)} className="h-9 rounded-md border border-input bg-background px-3 text-sm outline-none focus:border-primary">{noteCategories.map((item) => <option key={item}>{item}</option>)}</select></label><label className="grid gap-1.5 text-xs font-medium">标签<span className="font-normal text-muted-foreground">用逗号分隔</span><input value={tags} onChange={(event) => setTags(event.target.value)} className="h-9 rounded-md border border-input bg-background px-3 text-sm outline-none focus:border-primary" placeholder="VPS, 排障" /></label></div><label className="grid gap-1.5 text-xs font-medium">内容<textarea required value={content} onChange={(event) => setContent(event.target.value)} className="min-h-40 rounded-md border border-input bg-background px-3 py-2 text-sm outline-none focus:border-primary" placeholder="支持 Markdown 内容" /></label>{error && <p className="text-sm text-danger">{error}</p>}<div className="flex flex-col-reverse gap-2 border-t border-border pt-4 sm:flex-row sm:justify-end"><Button variant="outline" type="button" onClick={closeForm}>取消</Button><Button type="submit" disabled={!title.trim() || !content.trim()}>保存笔记</Button></div></form></Card></div>}
  </div>;
}
