import * as React from "react";
import { Check, Pencil, UserRound } from "lucide-react";
import { Badge, Button, Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui";
export interface GeneralState { name: string; space: string; }
export function GeneralSettings({ state, onChange, saved, onSaved }: { state: GeneralState; onChange: (state: GeneralState) => void; saved: boolean; onSaved: () => void }) {
  const [editing, setEditing] = React.useState(false); const [draft, setDraft] = React.useState(state);
  function save() { onChange({ name: draft.name.trim() || state.name, space: draft.space.trim() || state.space }); setEditing(false); onSaved(); }
  return <Card><CardHeader><CardTitle>个人信息</CardTitle><CardDescription>用于识别当前控制台与工作空间。</CardDescription></CardHeader><CardContent>{!editing ? <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-full bg-primary/15 text-lg font-semibold text-primary" aria-label="头像 C">C</div><div><p className="font-medium">{state.name}</p><div className="mt-1 flex items-center gap-2 text-xs text-muted-foreground"><UserRound className="h-3.5 w-3.5" aria-hidden="true" />{state.space}<Badge variant="neutral">个人空间</Badge></div></div></div><Button variant="secondary" size="sm" onClick={() => { setDraft(state); setEditing(true); }}><Pencil className="h-3.5 w-3.5" aria-hidden="true" />编辑个人信息</Button></div> : <form onSubmit={(e) => { e.preventDefault(); save(); }} className="space-y-3"><div className="grid gap-3 sm:grid-cols-2"><label className="space-y-1.5 text-xs text-muted-foreground">姓名<input value={draft.name} onChange={(e) => setDraft({ ...draft, name: e.target.value })} className="h-9 w-full rounded-md border border-input bg-background px-3 text-sm text-foreground" autoFocus /></label><label className="space-y-1.5 text-xs text-muted-foreground">空间名称<input value={draft.space} onChange={(e) => setDraft({ ...draft, space: e.target.value })} className="h-9 w-full rounded-md border border-input bg-background px-3 text-sm text-foreground" /></label></div><div className="flex gap-2"><Button type="submit" size="sm"><Check className="h-3.5 w-3.5" aria-hidden="true" />保存</Button><Button type="button" variant="ghost" size="sm" onClick={() => setEditing(false)}>取消</Button></div></form>}{saved && <p className="mt-3 text-xs text-success" role="status">已保存到当前会话</p>}</CardContent></Card>;
}
